baseurl = "http://replace-this-with-your-domain.com/"
title = "Ghostwriter example"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Ghostwriter example"
    description = "Ghostwriter example description"
    github = "https://github.com/XXX"
    linkedin = "https://linkedin.com/in/XXX/"
    gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/XXX"
    stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4